version: '2'
services:
  ognion-boilerplate-postgresql:
    image: postgres:9.6.5
    environment:
      - POSTGRES_USER=tpCi
      - POSTGRES_PASSWORD=someNotSecurePassword
    ports:
      - 5432:5432